### ISSUE TITLE
Vite Implementation with MMD WASM

### ISSUE THREAD

**Issue by SavAct** [noname0310/babylon-mmd-viewer#1]
I am using your project with Vite instead of Webpack, because it loads way faster. But I do not get it to run by using the mmd wasm libraries. Do you mind showcasing a Vite implementation instead of webpack? In any case, I appreciate your work.

**Comment by noname0310** [comment]
It will take me a while as I have never used vite before. I'll create a showcase and share the link here

**Comment by SavAct** [comment]
This is my `vite.config.js` that works with the non wasm implementation of babylon-mmd:
```js
import { defineConfig } from 'vite'
import basicSsl from '@vitejs/plugin-basic-ssl'
import { viteStaticCopy } from 'vite-plugin-static-copy'

export default defineConfig({   
  plugins: [
    basicSsl(),
    viteStaticCopy({
      targets: [
        { src: ['res/*', '!res/private_test'], dest: './res' },
      ]
    }),
  ],
  optimizeDeps: {
    exclude: ['@babylonjs/havok'],
},
server: {
    host: '0.0.0.0',
    port: 20310,
    https: true,
  },
  build: {
    rollupOptions: {
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
      }
    }
  },
})
```

**Comment by noname0310** [comment]
There was an issue with runtime errors in the browser-native ESM environment, [I fixed it](https://github.com/noname0310/babylon-mmd/commit/01e8f0095c3484a2214f30616a56bda20b856d7b) and here is a template for the `MmdWasmRuntime` that works with vite.

https://github.com/noname0310/babylon-mmd-vite-template

There seems to be an issue with shader code side effects not being handled properly. This is being fixed in this repository by adding the side effects directly as import statements

I'll close the issue for now, but if this doesn't solve your problem, please open an issue on the [babylon-mmd](https://github.com/noname0310/babylon-mmd) repository
